version: '3.8'

services:
  webgl:
    container_name: unity-webgl-static-site
    image: unity-webgl-static-site
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/webgl:/webgl
